import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { ArrowRight, CheckCircle2, ImagePlus, PackagePlus, Settings2, Sparkles } from "lucide-react";
import { Link } from "wouter";

const statCards = [
  { key: "total", label: "Productos totales", accent: "bg-[#211f1c]" },
  { key: "published", label: "Publicados", accent: "bg-[#f33825]" },
  { key: "drafts", label: "Borradores", accent: "bg-[#c79a44]" },
  { key: "archived", label: "Archivados", accent: "bg-[#81796e]" },
] as const;

export default function AdminDashboard() {
  const dashboard = trpc.admin.dashboard.useQuery();
  const stats = dashboard.data?.products ?? { total: 0, published: 0, drafts: 0, archived: 0 };

  return <DashboardLayout><div className="mx-auto max-w-[1400px] space-y-8">
    <header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="casacas-kicker">CASACAS LB / ADMINISTRACIÓN</p><h1 className="mt-3 font-display text-6xl leading-[.82] text-[#211f1c] sm:text-8xl">El centro<br /><span className="text-[#f33825]">de mando.</span></h1><p className="mt-5 max-w-xl text-sm leading-6 text-[#706a62]">Gestioná el catálogo, los precios y la publicación de tus productos desde un solo lugar.</p></div><Link href="/admin/products" className="inline-flex items-center justify-center gap-3 rounded-full bg-[#f33825] px-5 py-3 text-xs font-black uppercase tracking-[.14em] text-white transition hover:scale-[1.03] hover:rotate-[-2deg]">Nuevo producto <ArrowRight className="h-4 w-4" /></Link></header>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{statCards.map(card => <div key={card.key} className="overflow-hidden rounded-[24px] border border-[#d9d1c5] bg-[#f8f5ef] shadow-[0_12px_40px_rgba(40,34,27,.05)]"><div className={`h-1.5 ${card.accent}`} /><div className="p-5"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#81796e]">{card.label}</p><p className="mt-4 font-display text-6xl leading-none text-[#211f1c]">{dashboard.isLoading ? "—" : stats[card.key]}</p></div></div>)}</div>
    <div className="grid gap-6 xl:grid-cols-[1.35fr_.65fr]">
      <section className="rounded-[28px] border border-[#d9d1c5] bg-[#f8f5ef] p-6 shadow-[0_12px_40px_rgba(40,34,27,.05)] sm:p-8"><div className="flex items-start justify-between gap-5"><div><p className="casacas-kicker">PRÓXIMO PASO</p><h2 className="mt-2 font-display text-4xl leading-none text-[#211f1c]">Cargá tus productos reales.</h2><p className="mt-3 max-w-lg text-sm leading-6 text-[#706a62]">La base ya está preparada para que cada producto tenga precio, categoría, estado, descripción e imágenes.</p></div><div className="hidden h-14 w-14 shrink-0 rotate-[-8deg] place-items-center rounded-2xl bg-[#f33825] text-white sm:grid"><Sparkles /></div></div><div className="mt-8 grid gap-3 sm:grid-cols-3"><Link href="/admin/products" className="group rounded-2xl border border-[#d9d1c5] bg-[#eee9df] p-4 transition hover:-translate-y-1 hover:border-[#f33825]"><PackagePlus className="h-5 w-5 text-[#f33825]" /><p className="mt-7 text-sm font-bold text-[#211f1c]">Crear producto</p><p className="mt-1 text-xs leading-5 text-[#81796e]">Cargá nombre, precio y estado.</p><ArrowRight className="mt-4 h-4 w-4 transition group-hover:translate-x-1" /></Link><div className="rounded-2xl border border-[#d9d1c5] bg-[#eee9df] p-4"><ImagePlus className="h-5 w-5 text-[#c79a44]" /><p className="mt-7 text-sm font-bold text-[#211f1c]">Imágenes</p><p className="mt-1 text-xs leading-5 text-[#81796e]">La carga multimedia será el siguiente bloque.</p><span className="mt-4 inline-block text-[9px] font-black uppercase tracking-[.14em] text-[#a39a8f]">Preparado</span></div><div className="rounded-2xl border border-[#d9d1c5] bg-[#eee9df] p-4"><Settings2 className="h-5 w-5 text-[#81796e]" /><p className="mt-7 text-sm font-bold text-[#211f1c]">Configuración</p><p className="mt-1 text-xs leading-5 text-[#81796e]">WhatsApp, Instagram y datos del local.</p><span className="mt-4 inline-block text-[9px] font-black uppercase tracking-[.14em] text-[#a39a8f]">Siguiente módulo</span></div></div></section>
      <section className="rounded-[28px] bg-[#211f1c] p-6 text-[#f8f5ef] shadow-[0_12px_40px_rgba(40,34,27,.12)] sm:p-8"><p className="casacas-kicker text-[#f33825]">CHECKLIST V2.0</p><h2 className="mt-3 font-display text-4xl leading-none">Una base<br />ordenada.</h2><ul className="mt-8 space-y-5 text-sm text-[#d9d2c7]"><li className="flex gap-3"><CheckCircle2 className="h-5 w-5 shrink-0 text-[#f33825]" /><span>Acceso privado para el administrador.</span></li><li className="flex gap-3"><CheckCircle2 className="h-5 w-5 shrink-0 text-[#f33825]" /><span>Productos separados de la página pública.</span></li><li className="flex gap-3"><CheckCircle2 className="h-5 w-5 shrink-0 text-[#f33825]" /><span>Estados para borrador, publicado y archivado.</span></li><li className="flex gap-3"><CheckCircle2 className="h-5 w-5 shrink-0 text-[#f33825]" /><span>Precios listos para administrarse sin tocar código.</span></li></ul><div className="mt-10 border-t border-[#514c45] pt-5 text-[10px] font-black uppercase tracking-[.16em] text-[#8e887f]">Instagram oficial <span className="text-white">@casacaslb</span></div></section>
    </div>
  </div></DashboardLayout>;
}
